version: "2.1"

networks:
  airport-net:
    driver: bridge

services:
  server:
    container_name: server-container
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - airport-net

  redis:
    container_name: redis-container
    image: redis
    expose:
      - 6379
    volumes:
      - "redis_data:/data"
    networks:
      - airport-net
  
  db:
    container_name: db-container
    image: mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_INITDB_CHARSET: ${DB_INITDB_CHARSET}
      MYSQL_AUTHENTICATION_PLUGIN: caching_sha2_password
    volumes:
      - db_data:/var/lib/mysql
      - ./server/databases/schemas/airproject.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3307:3306"
    networks:
      - airport-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u root", "-p ${DB_PASSWORD}"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 0s
  
  phpmyadmin:
    container_name: phpmyadmin-container
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - airport-net

volumes:
  redis_data:
  db_data:
