name: Build and Test

on:
  push:
    branches:
      - test/actions
  pull_request:
    branches:
      - test/actions

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and run containers
      run: docker-compose up --build -d

    - name: Run test - GET Request to '/'
      run: docker exec server-container curl http://localhost:3000
      
    - name: Run test - POST Request to '/login' as ADMIN
      run: response=$(docker exec server-container curl -i -X POST -H 'Content-Type:application/json' -d '{"email":"belen@gmail.com", "password":"123"}' http://localhost:3000/login)
            accessToken=$(echo "$response" | grep -oP 'Set-Cookie:accessToken=[^;]+')
            refreshToken=$(echo "$response" | grep -oP 'Set-Cookie:refreshToken=[^;]+')

    - name: Run test - GET Request to '/users/id/:iduser'
      run: docker exec server-container curl -b "accessToken=$accessToken; refreshToken=$refreshToken;" http://localhost:3000/users/id/1

    - name: Stop and remove containers
      run: docker-compose down -v